config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  resources :articles do
    collection do
      get :manage
      get :not_permission
    end
  end
  devise_for :users
  get 'authors', to: 'users#author'
  get 'authors/:id', to: 'users#article_by_author'
  get 'manager', to: 'users#account_manage'
  get 'users/manager', to: 'users#manage'
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_rich_text :body
  resourcify
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: %i[edit update new destory manage create]
  before_action :get_article, only: %i[edit update show destroy]

  def index
    @pagy, @articles = pagy(Article.all, items: 4)
  end

  def show
    # show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    current_user.add_role :own, @article
    if @article.save
      redirect_to manage_articles_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    # edit
  end

  def update
    authorize @article
    if @article.update(article_params)
      redirect_to manage_articles_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @article
    @article.destroy
    redirect_to manage_articles_path, status: :see_other
  end

  def manage
    @author_name = User.find(current_user.id).fullname
    @articles = Article.where(user_id: current_user.id)
  end

  def not_permission
    # Not Enough Permission Access Article
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :publish)
  end

  def get_article
    @article = Article.find(params[:id])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.slim
= simple_form_for article do |form|
    = form.input :title
    .content_wrapper
        label Body
        div
            = form.rich_text_area :body
    = form.input :publish, label: "Want you pushlish this article? If true need check"
    = form.button :submit

app/views/articles/edit.slim
.wrapper
    = render "layouts/navbar"
    .content-article-edit-wrapper
        h2 Edit article
        = render "form", article: @article

app/views/articles/index.slim
.wrapper
    = render "layouts/navbar"
    .content-article-wrapper
        h2 Articles
        .list
            - @articles.each do |article|
                .article-item[data-controller="navigation" data-action="click->navigation#navigate" data-navigation-target="path" data-content="/articles/#{article.id}"]
                    .header
                        .author = User.find(article.user_id).fullname
                        .time = article.updated_at
                    .title-article = article.title
    == pagy_nav(@pagy)

app/views/articles/manage.slim
.wrapper-frame
    = render "layouts/manager_bar"
    .content-account-setting
        .content-article-manage-wrapper
            h2 = "Articles By " +  @author_name
            .list
                - @articles.each do |article|
                    .article-item
                        .header
                            .author = User.find(article.user_id).fullname
                            .time = article.updated_at
                        .body
                            .title-article = article.title
                            .control-wrapper
                                = button_to "View", article_path(article), method: :get, class: "view-btn"
                                = button_to "Edit", edit_article_path(article), method: :get, class: "edit-btn"
                                = button_to "Delete", article, method: :delete, class: "delete-btn", data: { confirm: 'Are you sure?' }

app/views/articles/new.slim
.wrapper-frame
    = render "layouts/manager_bar"
    .content-account-setting
        .content-article-new-wrapper
            h2 New article
            = render "form", article: @article

app/views/articles/not_permission.slim
.wrapper-error
    = image_tag "not_permission.jpg", class: "not-permission-img"
    .not-permission-wrapper
        .title Insufficient Permissions
        .content You enough not permissions to change this articles

app/views/articles/show.slim
.wrapper
    = render "layouts/navbar"
    .content-article-show-wrapper
        .title-article
            h2 = @article.title
            .time-article = @article.updated_at
        .author-article = "Author: " + User.find(@article.user_id).fullname
        .content-article == @article.body