config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  resources :articles do
    collection do
      get :manage
      get :not_permission
    end
  end
  devise_for :users
  get 'authors', to: 'users#author'
  get 'authors/:id', to: 'users#article_by_author'
  get 'manager', to: 'users#account_manage'
  get 'users/manager', to: 'users#manage'
end

app/views/layouts/_manager_bar.slim
.manager-bar
    .header
        .user_name = current_user.fullname
        .article_num = "Articles: " + Article.where(user_id: current_user.id).count().to_s
    .menu
        = link_to "New articles", new_article_path, class: "menu-item"
        = link_to "Manage articles", manage_articles_path, class: "menu-item"
        = link_to "Edit account", edit_user_registration_path, class: "menu-item"
        - if current_user.has_role? :admin
            = link_to "User Manage", users_manager_path, class: "menu-item"
        = button_to "Logout" , destroy_user_session_path,  :method => :delete,class: "logout-item", form_class: "logout-form"

app/views/layouts/_navbar.slim
.navbar-wrapper
    .left-navbar
        .logo TechBlog
        .menu
            = link_to "Home", articles_path, class: "item"
            = link_to "Author", "/authors", class: "item"
            = link_to "About", articles_path, class: "item"
            = link_to "Support", articles_path, class: "item"
        input.search-bar[type="text"  placeholder="Search articles..."]
    .right-navbar
        - if user_signed_in?
            .username[data-controller="navigation" data-navigation-target="path" data-action="click->navigation#navigate" data-content="/manager"]
                = current_user.fullname
            = button_to "Logout" , destroy_user_session_path,  method:  :delete,class: "logout", form_class: "logout-form"
        - else
            = link_to "Login", new_user_session_path, class: "login"
            = link_to "Signup", new_user_registration_path, class: "signup"

app/views/layouts/application.slim
doctype html
html
    head
        title Techblogapp
        meta[name="viewport" content="width=device-width,initial-scale=1"]
        = csrf_meta_tags
        = csp_meta_tag
        = stylesheet_link_tag "application", "data-turbo-track": "reload"
        = javascript_importmap_tags
    body
        = yield